variables:
  Agent.Source.Git.ShallowFetchDepth: 1
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"

jobs:
- template: azure-templates.yml
  parameters:
    name: Linux_27_offline
    os: linux
    tox: py27-offline --

- template: azure-templates.yml
  parameters:
    name: macOS_37_offline
    os: macos
    tox: py37-offline --

- template: azure-templates.yml
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline --

- template: azure-templates.yml
  parameters:
    name: Linux_37_online
    os: linux
    tox: py37-online --

- template: azure-templates.yml
  parameters:
    name: Linux_37_sunpydev
    os: linux
    tox: py37-sunpydev --
